export type Stat = {
    label: 'Height' | 'Weight' | 'Career Goals' | 'Club';
    value: string | number;
    icon: React.ComponentType<{ className?: string }>;
};

export type PlayerStatistic = {
  id: string;
  userId: string;
  displayName?: string;
  photoURL?: string;
  clubGuessrGamesPlayed?: number;
  clubGuessrGamesWon?: number;
  statDetectiveGamesPlayed?: number;
  statDetectiveGamesWon?: number;
  footballerFaceoffGamesPlayed?: number;
  footballerFaceoffGamesWon?: number;
  coins?: number;
  purchasedThemes?: string[];
  purchasedBadges?: string[];
  equippedBadge?: string;
  purchasedClues?: number;
  totalWins?: number;
};

export type UserProfile = {
  id: string;
  displayName: string;
  photoURL: string;
};

export type Message = {
    id: string;
    userId: string;
    displayName: string;
    photoURL: string;
    text: string;
    createdAt: any; // Firestore Timestamp
};


export type Footballer = {
  id: number;
  name: string;
  stats: {
    height: string;
    weight: string;
    careerGoals: number;
    club: string;
  };
  portraitImageUrlId: string;
};

export const footballers: Footballer[] = [
  { id: 1, name: 'Lionel Messi', stats: { height: '170cm', weight: '72kg', careerGoals: 837, club: 'Inter Miami' }, portraitImageUrlId: 'portrait-messi' },
  { id: 2, name: 'Cristiano Ronaldo', stats: { height: '187cm', weight: '83kg', careerGoals: 895, club: 'Al Nassr' }, portraitImageUrlId: 'portrait-cronaldo' },
  { id: 3, name: 'Kylian Mbappé', stats: { height: '178cm', weight: '73kg', careerGoals: 330, club: 'Real Madrid' }, portraitImageUrlId: 'portrait-mbappe' },
  { id: 4, name: 'Erling Haaland', stats: { height: '194cm', weight: '88kg', careerGoals: 260, club: 'Manchester City' }, portraitImageUrlId: 'portrait-haaland' },
  { id: 5, name: 'Mohamed Salah', stats: { height: '175cm', weight: '71kg', careerGoals: 357, club: 'Liverpool' }, portraitImageUrlId: 'portrait-salah' },
  { id: 6, name: 'Kevin De Bruyne', stats: { height: '181cm', weight: '68kg', careerGoals: 180, club: 'Manchester City' }, portraitImageUrlId: 'portrait-debruyne' },
  { id: 7, name: 'Luka Modrić', stats: { height: '172cm', weight: '66kg', careerGoals: 100, club: 'AC Milan' }, portraitImageUrlId: 'portrait-modric' },
  { id: 8, name: 'Neymar Jr', stats: { height: '175cm', weight: '68kg', careerGoals: 439, club: 'Al Hilal' }, portraitImageUrlId: 'portrait-neymar' },
  { id: 9, name: 'Harry Kane', stats: { height: '188cm', weight: '86kg', careerGoals: 400, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-kane' },
  { id: 10, name: 'Robert Lewandowski', stats: { height: '185cm', weight: '81kg', careerGoals: 650, club: 'Barcelona' }, portraitImageUrlId: 'portrait-lewandowski' },
  { id: 11, name: 'Virgil van Dijk', stats: { height: '193cm', weight: '92kg', careerGoals: 50, club: 'Liverpool' }, portraitImageUrlId: 'portrait-vandijk' },
  { id: 12, name: 'Jude Bellingham', stats: { height: '186cm', weight: '75kg', careerGoals: 60, club: 'Real Madrid' }, portraitImageUrlId: 'portrait-bellingham' },
  { id: 13, name: 'Vinícius Júnior', stats: { height: '176cm', weight: '73kg', careerGoals: 120, club: 'Real Madrid' }, portraitImageUrlId: 'portrait-vinicius' },
  { id: 14, name: 'Bukayo Saka', stats: { height: '178cm', weight: '65kg', careerGoals: 80, club: 'Arsenal' }, portraitImageUrlId: 'portrait-saka' },
  { id: 15, name: 'Phil Foden', stats: { height: '171cm', weight: '70kg', careerGoals: 90, club: 'Manchester City' }, portraitImageUrlId: 'portrait-foden' },
  { id: 16, name: 'Jamal Musiala', stats: { height: '184cm', weight: '72kg', careerGoals: 70, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-musiala' },
  { id: 17, name: 'Pelé', stats: { height: '173cm', weight: '73kg', careerGoals: 767, club: 'New York Cosmos' }, portraitImageUrlId: 'portrait-pele' },
  { id: 18, name: 'Diego Maradona', stats: { height: '165cm', weight: '70kg', careerGoals: 345, club: 'Boca Juniors' }, portraitImageUrlId: 'portrait-maradona' },
  { id: 19, name: 'Johan Cruyff', stats: { height: '180cm', weight: '75kg', careerGoals: 425, club: 'Feyenoord' }, portraitImageUrlId: 'portrait-cruyff' },
  { id: 20, name: 'Zinedine Zidane', stats: { height: '185cm', weight: '80kg', careerGoals: 125, club: 'Real Madrid' }, portraitImageUrlId: 'portrait-zidane' },
  { id: 21, name: 'Ronaldo Nazario', stats: { height: '183cm', weight: '90kg', careerGoals: 414, club: 'Corinthians' }, portraitImageUrlId: 'portrait-ronaldo' },
  { id: 22, name: 'Ronaldinho', stats: { height: '181cm', weight: '80kg', careerGoals: 313, club: 'Fluminense' }, portraitImageUrlId: 'portrait-ronaldinho' },
  { id: 23, name: 'Paolo Maldini', stats: { height: '186cm', weight: '85kg', careerGoals: 33, club: 'AC Milan' }, portraitImageUrlId: 'portrait-maldini' },
  { id: 24, name: 'Thierry Henry', stats: { height: '188cm', weight: '83kg', careerGoals: 411, club: 'New York Red Bulls' }, portraitImageUrlId: 'portrait-henry' },
  { id: 25, name: 'Lev Yashin', stats: { height: '189cm', weight: '82kg', careerGoals: 0, club: 'Dynamo Moscow' }, portraitImageUrlId: 'portrait-yashin' },
  { id: 28, name: 'Zlatan Ibrahimović', stats: { height: '195cm', weight: '95kg', careerGoals: 573, club: 'AC Milan' }, portraitImageUrlId: 'portrait-ibrahimovic' },
  { id: 30, name: 'Dennis Bergkamp', stats: { height: '183cm', weight: '78kg', careerGoals: 303, club: 'Arsenal' }, portraitImageUrlId: 'portrait-bergkamp' },
  { id: 31, name: 'Patrick Vieira', stats: { height: '193cm', weight: '83kg', careerGoals: 57, club: 'Manchester City' }, portraitImageUrlId: 'portrait-vieira' },
  { id: 32, name: 'Roy Keane', stats: { height: '180cm', weight: '76kg', careerGoals: 76, club: 'Celtic' }, portraitImageUrlId: 'portrait-keane' },
  { id: 33, name: 'Paul Scholes', stats: { height: '168cm', weight: '70kg', careerGoals: 155, club: 'Manchester United' }, portraitImageUrlId: 'portrait-scholes' },
  { id: 34, name: 'Ryan Giggs', stats: { height: '179cm', weight: '71kg', careerGoals: 168, club: 'Manchester United' }, portraitImageUrlId: 'portrait-giggs' },
  { id: 35, name: 'David Beckham', stats: { height: '183cm', weight: '76kg', careerGoals: 146, club: 'Paris Saint-Germain' }, portraitImageUrlId: 'portrait-beckham' },
  { id: 36, name: 'Steven Gerrard', stats: { height: '183cm', weight: '83kg', careerGoals: 212, club: 'LA Galaxy' }, portraitImageUrlId: 'portrait-gerrard' },
  { id: 37, name: 'Frank Lampard', stats: { height: '184cm', weight: '89kg', careerGoals: 303, club: 'New York City FC' }, portraitImageUrlId: 'portrait-lampard' },
  { id: 38, name: 'John Terry', stats: { height: '187cm', weight: '90kg', careerGoals: 73, club: 'Aston Villa' }, portraitImageUrlId: 'portrait-terry' },
  { id: 39, name: 'Didier Drogba', stats: { height: '188cm', weight: '91kg', careerGoals: 368, club: 'Phoenix Rising' }, portraitImageUrlId: 'portrait-drogba' },
  { id: 40, name: 'Andrés Iniesta', stats: { height: '171cm', weight: '68kg', careerGoals: 104, 'club': 'Emirates Club' }, portraitImageUrlId: 'portrait-iniesta' },
  { id: 41, name: 'Xavi Hernandez', stats: { height: '170cm', weight: '68kg', careerGoals: 122, club: 'Al Sadd' }, portraitImageUrlId: 'portrait-xavi' },
  { id: 42, name: 'Carles Puyol', stats: { height: '178cm', weight: '80kg', careerGoals: 24, club: 'Barcelona' }, portraitImageUrlId: 'portrait-puyol' },
  { id: 43, name: 'Sergio Busquets', stats: { height: '189cm', weight: '76kg', careerGoals: 20, club: 'Inter Miami' }, portraitImageUrlId: 'portrait-busquets' },
  { id: 44, name: 'Gerard Piqué', stats: { height: '194cm', weight: '85kg', careerGoals: 68, club: 'Barcelona' }, portraitImageUrlId: 'portrait-pique' },
  { id: 45, name: 'Sergio Ramos', stats: { height: '184cm', weight: '82kg', careerGoals: 141, club: 'Sevilla' }, portraitImageUrlId: 'portrait-ramos' },
  { id: 46, name: 'Iker Casillas', stats: { height: '185cm', weight: '84kg', careerGoals: 0, club: 'Porto' }, portraitImageUrlId: 'portrait-casillas' },
  { id: 47, name: 'Manuel Neuer', stats: { height: '193cm', weight: '93kg', careerGoals: 0, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-neuer' },
  { id: 48, name: 'Gianluigi Buffon', stats: { height: '192cm', weight: '92kg', careerGoals: 0, club: 'Parma' }, portraitImageUrlId: 'portrait-buffon' },
  { id: 49, name: 'Oliver Kahn', stats: { height: '188cm', weight: '91kg', careerGoals: 0, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-kahn' },
  { id: 50, name: 'Peter Schmeichel', stats: { height: '193cm', weight: '92kg', careerGoals: 11, club: 'Manchester City' }, portraitImageUrlId: 'portrait-schmeichel' },
  { id: 51, name: 'Edwin van der Sar', stats: { height: '197cm', weight: '83kg', careerGoals: 1, club: 'Manchester United' }, portraitImageUrlId: 'portrait-vandersar' },
  { id: 52, name: 'Petr Čech', stats: { height: '196cm', weight: '90kg', careerGoals: 0, club: 'Arsenal' }, portraitImageUrlId: 'portrait-cech' },
  { id: 53, name: 'Fabio Cannavaro', stats: { height: '176cm', weight: '75kg', careerGoals: 16, club: 'Al-Ahli' }, portraitImageUrlId: 'portrait-cannavaro' },
  { id: 54, name: 'Alessandro Nesta', stats: { height: '187cm', weight: '79kg', careerGoals: 11, club: 'Montreal Impact' }, portraitImageUrlId: 'portrait-nesta' },
  { id: 55, name: 'Lilian Thuram', stats: { height: '185cm', weight: '80kg', careerGoals: 17, club: 'Barcelona' }, portraitImageUrlId: 'portrait-thuram' },
  { id: 56, name: 'Marcel Desailly', stats: { height: '185cm', weight: '88kg', careerGoals: 43, club: 'Qatar SC' }, portraitImageUrlId: 'portrait-desailly' },
  { id: 57, name: 'Laurent Blanc', stats: { height: '192cm', weight: '82kg', careerGoals: 153, club: 'Manchester United' }, portraitImageUrlId: 'portrait-blanc' },
  { id: 58, name: 'Fernando Hierro', stats: { height: '187cm', weight: '84kg', careerGoals: 163, club: 'Bolton Wanderers' }, portraitImageUrlId: 'portrait-hierro' },
  { id: 59, name: 'Ruud Gullit', stats: { height: '191cm', weight: '88kg', careerGoals: 233, club: 'Chelsea' }, portraitImageUrlId: 'portrait-gullit' },
  { id: 60, name: 'Marco van Basten', stats: { height: '188cm', weight: '80kg', careerGoals: 301, club: 'AC Milan' }, portraitImageUrlId: 'portrait-vanbasten' },
  { id: 61, name: 'Frank Rijkaard', stats: { height: '190cm', weight: '85kg', careerGoals: 104, club: 'Ajax' }, portraitImageUrlId: 'portrait-rijkaard' },
  { id: 62, name: 'Lothar Matthäus', stats: { height: '174cm', weight: '71kg', careerGoals: 227, club: 'MetroStars' }, portraitImageUrlId: 'portrait-matthaus' },
  { id: 63, name: 'Jürgen Klinsmann', stats: { height: '181cm', weight: '77kg', careerGoals: 299, club: 'Orange County Blue Star' }, portraitImageUrlId: 'portrait-klinsmann' },
  { id: 64, name: 'Karl-Heinz Rummenigge', stats: { height: '182cm', weight: '79kg', careerGoals: 309, club: 'Servette' }, portraitImageUrlId: 'portrait-rummenigge' },
  { id: 65, name: 'Hristo Stoichkov', stats: { height: '178cm', weight: '76kg', careerGoals: 301, club: 'D.C. United' }, portraitImageUrlId: 'portrait-stoichkov' },
  { id: 66, name: 'Gheorghe Hagi', stats: { height: '174cm', weight: '72kg', careerGoals: 283, club: 'Galatasaray' }, portraitImageUrlId: 'portrait-hagi' },
  { id: 67, name: 'Michael Laudrup', stats: { height: '183cm', weight: '78kg', careerGoals: 167, club: 'Ajax' }, portraitImageUrlId: 'portrait-mlaudrup' },
  { id: 68, name: 'Brian Laudrup', stats: { height: '186cm', weight: '80kg', careerGoals: 129, club: 'Ajax' }, portraitImageUrlId: 'portrait-blaudrup' },
  { id: 69, name: 'Roberto Baggio', stats: { height: '174cm', weight: '73kg', careerGoals: 318, club: 'Brescia' }, portraitImageUrlId: 'portrait-baggio' },
  { id: 70, name: 'Alessandro Del Piero', stats: { height: '174cm', weight: '73kg', careerGoals: 346, club: 'Delhi Dynamos' }, portraitImageUrlId: 'portrait-delpiero' },
  { id: 71, name: 'Francesco Totti', stats: { height: '180cm', weight: '82kg', careerGoals: 307, club: 'AS Roma' }, portraitImageUrlId: 'portrait-totti' },
  { id: 72, name: 'Gabriel Batistuta', stats: { height: '185cm', weight: '78kg', careerGoals: 356, club: 'Al-Arabi' }, portraitImageUrlId: 'portrait-batistuta' },
  { id: 73, name: 'Hernán Crespo', stats: { height: '184cm', weight: '81kg', careerGoals: 323, club: 'Parma' }, portraitImageUrlId: 'portrait-crespo' },
  { id: 74, name: 'Pavel Nedvěd', stats: { height: '177cm', weight: '73kg', careerGoals: 178, club: 'Juventus' }, portraitImageUrlId: 'portrait-nedved' },
  { id: 75, name: 'Andriy Shevchenko', stats: { height: '183cm', weight: '73kg', careerGoals: 373, club: 'Dynamo Kyiv' }, portraitImageUrlId: 'portrait-shevchenko' },
  { id: 76, name: 'Kaká', stats: { height: '186cm', weight: '82kg', careerGoals: 237, club: 'Orlando City' }, portraitImageUrlId: 'portrait-kaka' },
  { id: 77, name: 'Luís Figo', stats: { height: '180cm', weight: '75kg', careerGoals: 176, club: 'Inter Milan' }, portraitImageUrlId: 'portrait-figo' },
  { id: 78, name: 'Rui Costa', stats: { height: '180cm', weight: '74kg', careerGoals: 110, club: 'Benfica' }, portraitImageUrlId: 'portrait-ruicosta' },
  { id: 79, name: 'Deco', stats: { height: '174cm', weight: '73kg', careerGoals: 121, club: 'Fluminense' }, portraitImageUrlId: 'portrait-deco' },
  { id: 80, name: 'Clarence Seedorf', stats: { height: '176cm', weight: '80kg', careerGoals: 172, club: 'Botafogo' }, portraitImageUrlId: 'portrait-seedorf' },
  { id: 81, name: 'Edgar Davids', stats: { height: '169cm', weight: '68kg', careerGoals: 53, club: 'Barnet' }, portraitImageUrlId: 'portrait-davids' },
  { id: 82, name: 'Jaap Stam', stats: { height: '191cm', weight: '90kg', careerGoals: 19, club: 'Ajax' }, portraitImageUrlId: 'portrait-stam' },
  { id: 83, name: 'Raúl González', stats: { height: '180cm', weight: '68kg', careerGoals: 432, club: 'New York Cosmos' }, portraitImageUrlId: 'portrait-raul' },
  { id: 84, name: 'Fernando Morientes', stats: { height: '186cm', weight: '79kg', careerGoals: 250, club: 'Marseille' }, portraitImageUrlId: 'portrait-morientes' },
  { id: 85, name: 'Guti', stats: { height: '183cm', weight: '76kg', careerGoals: 99, club: 'Beşiktaş' }, portraitImageUrlId: 'portrait-guti' },
  { id: 86, name: 'Míchel Salgado', stats: { height: '174cm', weight: '73kg', careerGoals: 10, club: 'Blackburn Rovers' }, portraitImageUrlId: 'portrait-salgado' },
  { id: 87, name: 'Christian Vieri', stats: { height: '185cm', weight: '82kg', careerGoals: 259, club: 'Atalanta' }, portraitImageUrlId: 'portrait-vieri' },
  { id: 88, name: 'Filippo Inzaghi', stats: { height: '181cm', weight: '74kg', careerGoals: 313, club: 'AC Milan' }, portraitImageUrlId: 'portrait-inzaghi' },
  { id: 89, name: 'David Trezeguet', stats: { height: '190cm', weight: '80kg', careerGoals: 308, club: 'Pune City' }, portraitImageUrlId: 'portrait-trezeguet' },
  { id: 90, name: 'Michael Owen', stats: { height: '173cm', weight: '70kg', careerGoals: 262, club: 'Stoke City' }, portraitImageUrlId: 'portrait-owen' },
  { id: 91, name: 'Alan Shearer', stats: { height: '183cm', weight: '82kg', careerGoals: 409, club: 'Newcastle United' }, portraitImageUrlId: 'portrait-shearer' },
  { id: 92, name: 'Ian Wright', stats: { height: '175cm', weight: '73kg', careerGoals: 313, club: 'Burnley' }, portraitImageUrlId: 'portrait-wright' },
  { id: 93, name: 'Robbie Fowler', stats: { height: '175cm', weight: '73kg', careerGoals: 254, club: 'Muangthong United' }, portraitImageUrlId: 'portrait-fowler' },
  { id: 94, name: 'Wayne Rooney', stats: { height: '176cm', weight: '83kg', careerGoals: 366, club: 'D.C. United' }, portraitImageUrlId: 'portrait-rooney' },
  { id: 95, name: 'Robin van Persie', stats: { height: '183cm', weight: '71kg', careerGoals: 322, club: 'Feyenoord' }, portraitImageUrlId: 'portrait-vanpersie' },
  { id: 96, name: 'Ruud van Nistelrooy', stats: { height: '188cm', weight: '80kg', careerGoals: 382, club: 'Málaga' }, portraitImageUrlId: 'portrait-vannistelrooy' },
  { id: 97, name: 'Arjen Robben', stats: { height: '180cm', weight: '80kg', careerGoals: 246, club: 'Groningen' }, portraitImageUrlId: 'portrait-robben' },
  { id: 98, name: 'Wesley Sneijder', stats: { height: '170cm', weight: '67kg', careerGoals: 186, club: 'Al-Gharafa' }, portraitImageUrlId: 'portrait-sneijder' },
  { id: 99, name: 'Andrea Pirlo', stats: { height: '177cm', weight: '68kg', careerGoals: 115, club: 'New York City FC' }, portraitImageUrlId: 'portrait-pirlo' },
  { id: 100, name: 'Gennaro Gattuso', stats: { height: '177cm', weight: '77kg', careerGoals: 17, club: 'Sion' }, portraitImageUrlId: 'portrait-gattuso' },
  { id: 101, name: 'Daniele De Rossi', stats: { height: '184cm', weight: '83kg', careerGoals: 87, club: 'Boca Juniors' }, portraitImageUrlId: 'portrait-derossi' },
  { id: 102, name: 'Miroslav Klose', stats: { height: '184cm', weight: '84kg', careerGoals: 332, club: 'Lazio' }, portraitImageUrlId: 'portrait-klose' },
  { id: 103, name: 'Lukas Podolski', stats: { height: '182cm', weight: '83kg', careerGoals: 323, club: 'Górnik Zabrze' }, portraitImageUrlId: 'portrait-podolski' },
  { id: 104, name: 'Bastian Schweinsteiger', stats: { height: '183cm', weight: '79kg', careerGoals: 109, club: 'Chicago Fire' }, portraitImageUrlId: 'portrait-schweinsteiger' },
  { id: 105, name: 'Philipp Lahm', stats: { height: '170cm', weight: '66kg', careerGoals: 25, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-lahm' },
  { id: 106, name: 'Thomas Müller', stats: { height: '185cm', weight: '76kg', careerGoals: 310, club: 'Bayern Munich' }, portraitImageUrlId: 'portrait-muller' }
];

export const clubs = [
  "Inter Miami", "Al Nassr", "Real Madrid", "Manchester City", "Liverpool", "AC Milan", "Al Hilal", "Bayern Munich", "Barcelona", "Arsenal", "New York Cosmos", "Boca Juniors", "Feyenoord", "Corinthians", "Fluminense", "New York Red Bulls", "Dynamo Moscow", "Tottenham Hotspur", "Atlético Madrid", "Paris Saint-Germain", "Sevilla", "Manchester United", "AS Roma", "Inter Milan", "Celtic", "LA Galaxy", "New York City FC", "Aston Villa", "Phoenix Rising", "Emirates Club", "Al Sadd", "Porto", "Parma", "Al-Ahli", "Montreal Impact", "Qatar SC", "Bolton Wanderers", "Chelsea", "Ajax", "MetroStars", "Orange County Blue Star", "Servette", "D.C. United", "Galatasaray", "Brescia", "Delhi Dynamos", "Al-Arabi", "Juventus", "Dynamo Kyiv", "Orlando City", "Botafogo", "Barnet", "Marseille", "Beşiktaş", "Blackburn Rovers", "Atalanta", "Pune City", "Stoke City", "Newcastle United", "Burnley", "Muangthong United", "Málaga", "Groningen", "Al-Gharafa", "Sion", "Lazio", "Górnik Zabrze", "Chicago Fire"
];


export function getRandomFootballer(excludeIds: number[] | number = []): Footballer {
  const excluded = Array.isArray(excludeIds) ? excludeIds : [excludeIds];
  const available = footballers.filter((f) => !excluded.includes(f.id));
  if (available.length === 0) return footballers[0];
  const randomIndex = Math.floor(Math.random() * available.length);
  return available[randomIndex];
}


export type Translations = {
    [key: string]: string;
}

export const translations: {[lang: string]: Translations} = {
    en: {
        'app.title': 'Pixel Soccer Showdown',
        'app.description': 'Choose your challenge and prove you\'re the ultimate fan!',
        'game.club-guessr.title': 'Club Guessr',
        'game.club-guessr.description': 'Guess the player\'s current or most famous club.',
        'game.stat-detective.title': 'Stat Detective',
        'game.stat-detective.description': 'Identify the footballer by their stats.',
        'game.face-off.title': 'Footballer Face-off',
        'game.face-off.description': 'Challenge others in a 1v1 showdown.',
        'home.footer': 'Ready to climb the ranks?',
        'login.welcome': 'Welcome Back!',
        'login.signInMessage': 'Sign in to continue your soccer journey.',
        'login.signInButton': 'Sign In with Google',
        'profile.title': 'Your Profile',
        'profile.joined': 'Joined',
        'profile.totalWins': 'Total Wins',
        'profile.winRate': 'Win Rate',
        'profile.coins': 'Coins',
        'profile.performance': 'Performance',
        'profile.winsPerGame': 'Your wins per game mode',
        'profile.signOut': 'Sign Out',
        'profile.settings': 'Settings',
        'profile.language': 'Language',
        'profile.purchasedClues': 'Clues',
        'bottomNav.home': 'Home',
        'bottomNav.chat': 'Chat',
        'bottomNav.profile': 'Profile',
        'bottomNav.shop': 'Shop',
        'bottomNav.leaderboard': 'Leaderboard',
        'chat.title': 'Global Chat',
        'chat.placeholder': 'Type a message...',
        'chat.send': 'Send',
        'faceOff.title': 'Footballer Face-off',
        'faceOff.vs': 'VS',
        'faceOff.score': 'Score',
        'faceOff.whoIsThis': 'Who is this?',
        'faceOff.guessPlaceholder': 'Type your guess...',
        'faceOff.matchStarting': 'Finding opponent... Match will begin shortly!',
        'faceOff.pointYou': 'Point for you!',
        'faceOff.pointRival': 'Point for the rival!',
        'faceOff.pointBoth': 'You both got it!',
        'faceOff.draw': 'It\'s a Draw!',
        'faceOff.wins': 'wins',
        'faceOff.finalScore': 'Final Score',
        'clubGuessr.title': 'Club Guessr',
        'clubGuessr.guessPlaceholder': 'Who is this?',
        'clubGuessr.submitGuess': 'Submit Guess',
        'clubGuessr.correctToast.title': 'Correct!',
        'clubGuessr.correctToast.description': 'You guessed {playerName}!',
        'clubGuessr.coinsAdded': '+10 Coins!',
        'clubGuessr.incorrectToast.title': 'Incorrect!',
        'clubGuessr.incorrectToast.description': 'That\'s not the right club. Try again!',
        'clubGuessr.youGotIt': 'You got it!',
        'clubGuessr.niceTry': 'Nice try!',
        'clubGuessr.playerWas': 'The player was {playerName}',
        'clubGuessr.nextPlayer': 'Next Player',
        'clubGuessr.getClue': 'Get a Clue (Reveal Stat)',
        'clue.smartClue': 'Smart Clue',
        'clue.left': 'left',
        'clue.noClues': 'No clues left!',
        'clue.buyMore': 'You can buy more clues from the shop.',
        'stat.title': 'Stat Detective',
        'stat.attemptsLeft': 'You have {attemptsLeft} {attempts, plural, one {attempt} other {attempts}} left.',
        'stat.whoAmI': 'Who Am I?',
        'stat.guessPlaceholder': 'Enter player\'s name',
        'stat.submitGuess': 'Submit Guess',
        'stat.correctToast.title': 'Correct!',
        'stat.correctToast.description': 'You guessed {playerName}!',
        'stat.coinsAdded': '+10 Coins!',
        'stat.incorrectToast.title': 'Incorrect!',
        'stat.incorrectToast.description': 'That\'s not the right player. Try again!',
        'stat.gameOver': 'Game Over!',
        'stat.youGotIt': 'You got it!',
        'stat.playerWas': 'The player was {playerName}',
        'stat.playAgain': 'Play Again',
        'stat.yourGuesses': 'Your Guesses',
        'stat.getClue': 'Get a Clue (Level {clueLevel})',
        'stat.height': 'Height',
        'stat.weight': 'Weight',
        'stat.club': 'Club',
        'stat.careerGoals': 'Career Goals',
        'lang.en': 'English',
        'lang.ru': 'Russian',
        'lang.uz': 'Uzbek',
        'shop.title': 'Shop',
        'shop.themes': 'Themes',
        'shop.badges': 'Profile Badges',
        'shop.badge.shield': 'Starter Shield',
        'shop.badge.gem': 'Pro Gem',
        'shop.badge.crown': 'King\'s Crown',
        'shop.badge.star': 'All-Star Player',
        'shop.badge.medal': 'G.O.A.T. Medal',
        'shop.badge.trophy': 'Champion\'s Trophy',
        'shop.badgeEquipped': 'Badge Equipped!',
        'shop.consumables': 'Consumables',
        'shop.cluePack': 'Clue Pack (5 Clues)',
        'shop.theme.golden': 'Golden Goal Theme',
        'shop.buy': 'Buy',
        'shop.equip': 'Equip',
        'shop.equipped': 'Equipped',
        'shop.insufficientCoins': 'Insufficient coins!',
        'shop.purchaseSuccess': 'Purchase successful!',
        'leaderboard.title': 'Leaderboard',
        'leaderboard.rank': 'Rank',
        'leaderboard.player': 'Player',
        'leaderboard.wins': 'Wins',
        'leaderboard.coins': 'Coins',
        'leaderboard.totalWins': 'Total Wins',
        'leaderboard.loading': 'Loading top players...',
        'leaderboard.noPlayers': 'No players on the leaderboard yet. Be the first!',
    },
    ru: {
        'app.title': 'Пиксельный Футбольный Поединок',
        'app.description': 'Выберите испытание и докажите, что вы лучший фанат!',
        'game.club-guessr.title': 'Угадай клуб',
        'game.club-guessr.description': 'Угадайте текущий или самый известный клуб игрока.',
        'game.stat-detective.title': 'Статистический детектив',
        'game.stat-detective.description': 'Определите футболиста по его статистике.',
        'game.face-off.title': 'Футбольный поединок',
        'game.face-off.description': 'Соревнуйтесь с другими в поединке 1 на 1.',
        'home.footer': 'Готовы подняться в рейтинге?',
        'login.welcome': 'С возвращением!',
        'login.signInMessage': 'Войдите, чтобы продолжить свой футбольный путь.',
        'login.signInButton': 'Войти через Google',
        'profile.title': 'Ваш профиль',
        'profile.joined': 'Присоединился',
        'profile.totalWins': 'Всего побед',
        'profile.winRate': 'Процент побед',
        'profile.coins': 'Монеты',
        'profile.performance': 'Производительность',
        'profile.winsPerGame': 'Ваши победы в каждом режиме игры',
        'profile.signOut': 'Выйти',
        'profile.settings': 'Настройки',
        'profile.language': 'Язык',
        'profile.purchasedClues': 'Подсказки',
        'bottomNav.home': 'Главная',
        'bottomNav.chat': 'Чат',
        'bottomNav.profile': 'Профиль',
        'bottomNav.shop': 'Магазин',
        'bottomNav.leaderboard': 'Рейтинг',
        'chat.title': 'Общий чат',
        'chat.placeholder': 'Введите сообщение...',
        'chat.send': 'Отправить',
        'faceOff.title': 'Футбольный поединок',
        'faceOff.vs': 'ПРОТИВ',
        'faceOff.score': 'Счет',
        'faceOff.whoIsThis': 'Кто это?',
        'faceOff.guessPlaceholder': 'Введите вашу догадку...',
        'faceOff.matchStarting': 'Поиск соперника... Матч скоро начнется!',
        'faceOff.pointYou': 'Очко вам!',
        'faceOff.pointRival': 'Очко сопернику!',
        'faceOff.pointBoth': 'Вы оба угадали!',
        'faceOff.draw': 'Ничья!',
        'faceOff.wins': 'победил',
        'faceOff.finalScore': 'Итоговый счет',
        'clubGuessr.title': 'Угадай клуб',
        'clubGuessr.guessPlaceholder': 'Кто это?',
        'clubGuessr.submitGuess': 'Отправить догадку',
        'clubGuessr.correctToast.title': 'Правильно!',
        'clubGuessr.correctToast.description': 'Вы угадали {playerName}!',
        'clubGuessr.coinsAdded': '+10 Монет!',
        'clubGuessr.incorrectToast.title': 'Неправильно!',
        'clubGuessr.incorrectToast.description': 'Это не тот клуб. Попробуйте еще раз!',
        'clubGuessr.youGotIt': 'Вы угадали!',
        'clubGuessr.niceTry': 'Хорошая попытка!',
        'clubGuessr.playerWas': 'Игроком был {playerName}',
        'clubGuessr.nextPlayer': 'Следующий игрок',
        'clubGuessr.getClue': 'Получить подсказку (раскрыть стату)',
        'clue.smartClue': 'Умная подсказка',
        'clue.left': 'осталось',
        'clue.noClues': 'Подсказок не осталось!',
        'clue.buyMore': 'Вы можете купить больше подсказок в магазине.',
        'stat.title': 'Статистический детектив',
        'stat.attemptsLeft': 'У вас осталось {attemptsLeft} {attempts, plural, one {попытка} few {попытки} many {попыток} other {попытки}}.',
        'stat.whoAmI': 'Кто я?',
        'stat.guessPlaceholder': 'Введите имя игрока',
        'stat.submitGuess': 'Отправить догадку',
        'stat.correctToast.title': 'Правильно!',
        'stat.correctToast.description': 'Вы угадали {playerName}!',
        'stat.coinsAdded': '+10 Монет!',
        'stat.incorrectToast.title': 'Неправильно!',
        'stat.incorrectToast.description': 'Это не тот игрок. Попробуйте еще раз!',
        'stat.gameOver': 'Игра окончена!',
        'stat.youGotIt': 'Вы угадали!',
        'stat.playerWas': 'Игроком был {playerName}',
        'stat.playAgain': 'Играть снова',
        'stat.yourGuesses': 'Ваши догадки',
        'stat.getClue': 'Получить подсказку (уровень {clueLevel})',
        'stat.height': 'Рост',
        'stat.weight': 'Вес',
        'stat.club': 'Клуб',
        'stat.careerGoals': 'Голы за карьеру',
        'lang.en': 'Английский',
        'lang.ru': 'Русский',
        'lang.uz': 'Узбекский',
        'shop.title': 'Магазин',
        'shop.themes': 'Темы',
        'shop.badges': 'Значки профиля',
        'shop.badge.shield': 'Щит новичка',
        'shop.badge.gem': 'Кристалл профи',
        'shop.badge.crown': 'Корона короля',
        'shop.badge.star': 'Звезда',
        'shop.badge.medal': 'Медаль G.O.A.T.',
        'shop.badge.trophy': 'Трофей чемпиона',
        'shop.badgeEquipped': 'Значок установлен!',
        'shop.consumables': 'Расходные материалы',
        'shop.cluePack': 'Набор подсказок (5 шт.)',
        'shop.theme.golden': 'Тема "Золотой гол"',
        'shop.buy': 'Купить',
        'shop.equip': 'Применить',
        'shop.equipped': 'Применено',
        'shop.insufficientCoins': 'Недостаточно монет!',
        'shop.purchaseSuccess': 'Покупка совершена успешно!',
        'leaderboard.title': 'Рейтинг',
        'leaderboard.rank': 'Ранг',
        'leaderboard.player': 'Игрок',
        'leaderboard.wins': 'Победы',
        'leaderboard.coins': 'Монеты',
        'leaderboard.totalWins': 'Всего побед',
        'leaderboard.loading': 'Загрузка лучших игроков...',
        'leaderboard.noPlayers': 'В рейтинге пока нет игроков. Будьте первым!',
    },
    uz: {
        'app.title': 'Piksel Futbol To\'qnashuvi',
        'app.description': 'O\'z chaqirig\'ingizni tanlang va eng zo\'r muxlis ekanligingizni isbotlang!',
        'game.club-guessr.title': 'Klubni Top',
        'game.club-guessr.description': 'O\'yinchining hozirgi yoki eng mashhur klubini toping.',
        'game.stat-detective.title': 'Statistik Detektiv',
        'game.stat-detective.description': 'Futbolchini statistik ma\'lumotlariga qarab aniqlang.',
        'game.face-off.title': 'Futbolchilar Janggi',
        'game.face-off.description': 'Boshqalar bilan 1v1 bahsda kuch sinashing.',
        'home.footer': 'Reytingda ko\'tarilishga tayyormisiz?',
        'login.welcome': 'Xush kelibsiz!',
        'login.signInMessage': 'Futbol sayohatingizni davom ettirish uchun tizimga kiring.',
        'login.signInButton': 'Google orqali kirish',
        'profile.title': 'Sizning profilingiz',
        'profile.joined': 'Qo\'shildi',
        'profile.totalWins': 'Jami g\'alabalar',
        'profile.winRate': 'G\'alaba darajasi',
        'profile.coins': 'Tangalar',
        'profile.performance': 'Natijadorlik',
        'profile.winsPerGame': 'Har bir o\'yin rejimidagi g\'alabalaringiz',
        'profile.signOut': 'Chiqish',
        'profile.settings': 'Sozlamalar',
        'profile.language': 'Til',
        'profile.purchasedClues': 'Maslahatlar',
        'bottomNav.home': 'Bosh sahifa',
        'bottomNav.chat': 'Suhbat',
        'bottomNav.profile': 'Profil',
        'bottomNav.shop': 'Do\'kon',
        'bottomNav.leaderboard': 'Reyting',
        'chat.title': 'Umumiy Suhbat',
        'chat.placeholder': 'Xabar yozing...',
        'chat.send': 'Yuborish',
        'faceOff.title': 'Futbolchilar Janggi',
        'faceOff.vs': 'VS',
        'faceOff.score': 'Hisob',
        'faceOff.whoIsThis': 'Bu kim?',
        'faceOff.guessPlaceholder': 'Taxminingizni yozing...',
        'faceOff.matchStarting': 'Raqib qidirilmoqda... O\'yin tez orada boshlanadi!',
        'faceOff.pointYou': 'Ochko sizga!',
        'faceOff.pointRival': 'Ochko raqibga!',
        'faceOff.pointBoth': 'Ikkalangiz ham topdingiz!',
        'faceOff.draw': 'Durrang!',
        'faceOff.wins': 'g\'alaba qozondi',
        'faceOff.finalScore': 'Yakuniy hisob',
        'clubGuessr.title': 'Klubni Top',
        'clubGuessr.guessPlaceholder': 'Bu kim?',
        'clubGuessr.submitGuess': 'Taxminni yuborish',
        'clubGuessr.correctToast.title': 'To\'g\'ri!',
        'clubGuessr.correctToast.description': 'Siz {playerName}ni topdingiz!',
        'clubGuessr.coinsAdded': '+10 Tanga!',
        'clubGuessr.incorrectToast.title': 'Noto\'g\'ri!',
        'clubGuessr.incorrectToast.description': 'Bu klub emas. Yana bir bor urinib ko\'ring!',
        'clubGuessr.youGotIt': 'Siz topdingiz!',
        'clubGuessr.niceTry': 'Yaxshi urinish!',
        'clubGuessr.playerWas': 'Futbolchi {playerName} edi',
        'clubGuessr.nextPlayer': 'Keyingi futbolchi',
        'clubGuessr.getClue': 'Yordam olish (Statistikani ochish)',
        'clue.smartClue': 'Aqlli yordam',
        'clue.left': 'qoldi',
        'clue.noClues': 'Maslahatlar qolmadi!',
        'clue.buyMore': 'Do\'kondan ko\'proq maslahat sotib olishingiz mumkin.',
        'stat.title': 'Statistik Detektiv',
        'stat.attemptsLeft': 'Sizda {attemptsLeft} ta urinish qoldi.',
        'stat.whoAmI': 'Men kimman?',
        'stat.guessPlaceholder': 'Futbolchi nomini kiriting',
        'stat.submitGuess': 'Taxminni yuborish',
        'stat.correctToast.title': 'To\'g\'ri!',
        'stat.correctToast.description': 'Siz {playerName}ni topdingiz!',
        'stat.coinsAdded': '+10 Tanga!',
        'stat.incorrectToast.title': 'Noto\'g\'ri!',
        'stat.incorrectToast.description': 'Bu boshqa futbolchi. Yana bir bor urinib ko\'ring!',
        'stat.gameOver': 'O\'yin tugadi!',
        'stat.youGotIt': 'Siz topdingiz!',
        'stat.playerWas': 'Futbolchi {playerName} edi',
        'stat.playAgain': 'Qayta o\'ynash',
        'stat.yourGuesses': 'Sizning taxminlaringiz',
        'stat.getClue': 'Yordam olish (Daraja {clueLevel})',
        'stat.height': 'Bo\'yi',
        'stat.weight': 'Vazni',
        'stat.club': 'Klub',
        'stat.careerGoals': 'Karyerasidagi gollar',
        'lang.en': 'Inglizcha',
        'lang.ru': 'Ruscha',
        'lang.uz': 'O\'zbekcha',
        'shop.title': 'Do\'kon',
        'shop.themes': 'Mavzular',
        'shop.badges': 'Profil nishonlari',
        'shop.badge.shield': 'Boshlang\'ich qalqoni',
        'shop.badge.gem': 'Professional gavhari',
        'shop.badge.crown': 'Qirol toji',
        'shop.badge.star': 'Yulduz O\'yinchi',
        'shop.badge.medal': 'G.O.A.T. Medali',
        'shop.badge.trophy': 'Chempion Kubogi',
        'shop.badgeEquipped': 'Nishon taqildi!',
        'shop.consumables': 'Sarf materiallari',
        'shop.cluePack': 'Maslahatlar to\'plami (5 ta)',
        'shop.theme.golden': '"Oltin To\'p" mavzusi',
        'shop.buy': 'Sotib olish',
        'shop.equip': 'Qo\'llash',
        'shop.equipped': 'Qo\'llanilgan',
        'shop.insufficientCoins': 'Tangalar yetarli emas!',
        'shop.purchaseSuccess': 'Muvaffaqiyatli xarid qilindi!',
        'leaderboard.title': 'Reyting',
        'leaderboard.rank': 'O\'rin',
        'leaderboard.player': 'O\'yinchi',
        'leaderboard.wins': 'G\'alabalar',
        'leaderboard.coins': 'Tangalar',
        'leaderboard.totalWins': 'Jami G\'alabalar',
        'leaderboard.loading': 'Eng yaxshi o\'yinchilar yuklanmoqda...',
        'leaderboard.noPlayers': 'Hozircha reytingda o\'yinchilar yo\'q. Birinchi bo\'ling!',
    },
};
